
def additoin(x, y):
    x = 10
    y = 20
    try:
        print("Addition:", x + b)
    except Exception as e:
        print("something went wrong" , e.__class__)
    else:
        print("the operation is successful")



additoin(10, 20)
